In [1]:
import os
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
path =  '/projects/0/FWC2/Spatial_dependence/Paper2'

In [3]:
basin = 'NEA'
cluster = 1

In [4]:
# Read files
geo_station = pd.read_pickle(os.path.join(path,'Station_geogunit107/'+basin+'/geogunit_station_{:s}.pkl'.format(basin)))
dmg_station = pd.read_csv(os.path.join(path,'Station_geogunit107/'+basin+'/damage_per_station_{:s}.csv'.format(basin)))
dmg_geo_perc = pd.read_pickle(os.path.join(path,'Station_geogunit107/'+basin+'/station_geoguint_dmg_perc_{:s}.pkl'.format(basin)))
station_geo = pd.read_pickle(os.path.join(path,'Station_geogunit107/'+basin+'/station_geoguint_{:s}.pkl'.format(basin)))

In [6]:
# Event folder
event_folder = os.path.join(path,'Eventset/'+basin+'/rp_event_set_cluster{:d}.pkl'.format(cluster))
station_folder = os.path.join(path,'Eventset/station_info.csv')

# Event damage
event_damage = pd.read_pickle(os.path.join(path,'Station_geogunit107/Damage_event/'+basin+'/damage_event_per_station_cluster{:d}.pkl'.format(cluster)))

In [7]:
event_damage

,1017,974,975,976,977,978,979,980,981,982,...,5688,5689,5690,5691,5692,5693,5694,5695,5696,5697
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36909,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36910,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36911,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36913,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
np.where(event_damage.sum(axis=1)>0)

(array([    4,     7,     9, ..., 36911, 36912, 36913]),)